name: RPGDore
version: '${project.version}'
main: net.danh.rpgdore.RPGDore
api-version: 1.13
authors: [ VoChiDanh ]
depend:
  - MMOItems
  - MythicLib
softdepend:
  - ShopGUIPlus
commands:
  RPGDore:
    usage: /RPGDore
    permission: RPGDore.admin
    aliases:
      - dore
permissions:
  RPGDore.admin:
    default: op
