name: RPGDore
version: '${project.version}'
main: net.danh.rpgdore.RPGDore
api-version: 1.13
authors: [ VoChiDanh ]
depend:
  - MMOItems
  - MythicLib
  - MythicMobs
commands:
  RPGDore:
    usage: /RPGDore
    permission: RPGDore.admin
    aliases:
      - dore
  class:
    usage: /Class
    permission: RPGDore.user
    aliases:
      - skill
permissions:
  RPGDore.admin:
    default: op
  RPGDore.user:
    default: true
